configuration: Release

# restore NuGet packages before running MSBuild 
before_build:
  - nuget restore

#package Web Application Project for Web Deploy 
build:
 verbosity: minimal
 publish_wap: true